### PR TITLE
Add base16-wmaker to list.yaml

### PR DESCRIPTION
**Pull request by d-torrance**

### CODE REVIEW

**Comment by joshgoebel** [comment]
Please rebase to resolve conflict?

**Review by joshgoebel — APPROVED** [review]

**Comment by d-torrance** [comment]
> Please rebase to resolve conflict?

Done!

**Comment by joshgoebel** [comment]
Now we wait.  I reached out to Chris to volunteer to help with PRs here.  If that happens we can clean up a lot of these open PRs I think.

**Comment by belak** [comment]
Looks good to me! Thanks!

**Pull request merged**
