### PR TITLE
Add highlightjs template for Highlight.js

### PR DESCRIPTION
**Pull request by joshgoebel**

### CODE REVIEW

**Comment by belak** [comment]
Looks good to me! It's awesome to see official hljs support!

**Comment by joshgoebel** [comment]
>  It's awesome to see official hljs support!

Well I think it can still be improved a bit and I'm trying to figure out how to deal with the fact that we already bundle many of these in the core library (but we don't want to bundle them all)... and that many in the core library aren't "correct" either in the spec sense... to trying to figure out what happens next. :-)  

Adding the template is just the beginning, LOL.

**Comment by belak** [comment]
If you're looking for a few specifics to include, the original few designed by Chris are the ones that make the most sense. I believe that's default-light, default-dark, ocean, eighties, tomorrow, and tomorrow-night. There may be others as well.

See https://github.com/chriskempson/base16-default-schemes and https://github.com/chriskempson/base16-tomorrow-scheme

**Comment by joshgoebel** [comment]
We already have MOST of those I think, though I do not know if they are "canonical" or not... when I started working on this I realizing that some of our  Base16 themes (Gruvbox for sure) just took the palette then "went wild" with their application of it... so that the build produces output that's entirely different... so yet another thing to deal with. :-)

**Pull request merged**
