### PR TITLE
Add dwm template, migrate from abandoned st template

### PR DESCRIPTION
**Pull request by dgmulf**
The original base16-st author is completely unresponsive to issue reports and pull requests, so I rewrote it from scratch, fixing some problems along the way. I also wrote a template for the dwm window manager.

### CODE REVIEW

**Comment by reyemxela** [comment]
This looks great, I'm just not quite sure of proper protocol/etiquette when nuking someone else's templates out of the list. The old repo does look pretty deserted, but it looks like @honza is still somewhat active on github?

Anyone have any input, or am I just overthinking this?

**Comment by honza** [comment]
wow

**Comment by belak** [comment]
I'm not entirely sure how to handle this. I would be happy to include dwm, but it seems like some sort of discussion needs to happen between @honza and @dgmulf. We don't currently have a policy for handling taking over a template, so you'll either need to work something out or add the alternate st under a different name.

**Comment by honza** [comment]
Take it. I don't have time to devote to this.

**Comment by belak** [comment]
Thanks for the update! If @dmgulf is still interested, we can move forward with this.

**Comment by dgmulf** [comment]
I'm totally fine with adding my template as an alternate under a different
name. I can't promise that I'll be able to indefinitely maintain it either.
Let me know what you prefer. :)

**Comment by belak** [comment]
Alright, sounds like everyone is on board. Thanks all!

**Pull request merged**
