### PR TITLE
add base16-fresobaldi to list

### PR DESCRIPTION
**Pull request by rkubosz**

### CODE REVIEW

**Comment by rkubosz** [comment]
Hello Chris!

I created this pull request moment after I published the base16-frescobaldi on github. I wrote about base16-frescobaldi on lilypond mailing list and I've just got an email from a Frescobaldi's mainainer about incorporating this themes into the application.This idea looks very good to me since Frescobaldi is a GUI application. Publishing it also here could confuse Frescobaldi's user. I'm asking you to not merge already this PR and wait for me for an update how things worked out.
I hope that you'll understand my project's current situation :-)

**Comment by chriskempson** [comment]
No problem, I'll wait for an update.

**Comment by belak** [comment]
Hello @rkubosz, has there been any updates on this? What's the status of this PR?

**Comment by rkubosz** [comment]
Hello @belak!
I've talked with maintainer of Frescobaldi. We decided, that we transfer the ownership of base16-frescobaldi to the frescobaldi project page and rename it to frescobaldi-themes.

https://github.com/frescobaldi/frescobaldi-themes

The previous link (www.github.com/rkubosz/base16-frescobaldi) still works and redirects to frescobaldi-themes.
The template is still compatible with base16 architecture and I want it to be. Themes for frescobaldi are building correctly with use of pybase16-builder, however, due to syntax of xml files they cannot be injected (injection of themes is a specific feature of pybase16-builder, it's a minor problem IMO).

The delay of this PR was caused by my concern of how thinks will work out with this base16-frescobaldi ownership, but now I can say it worked out well. Frescobaldi-themes is licensed under MIT. However, it is no longer compatible with the base16-* naming convention.

I leave the decision to you to merge this PR and https://github.com/chriskempson/base16/pull/196
I am happy that frescobaldi-themes is available to users of frescobaldi on it's github page. Publishing it here may also help users of frescobaldi to find this repo full of ready-to-use themes for their editor.

Thanks for your patience!

**Comment by belak** [comment]
Seems good to me. Thanks for being so patient!

**Pull request merged**
